# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'serial_port_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SerialPortWindow(object):
    def setupUi(self, SerialPortWindow):
        SerialPortWindow.setObjectName("SerialPortWindow")
        SerialPortWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(SerialPortWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(40, 40, 641, 261))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(20, 80, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.com_list_combobox = QtWidgets.QComboBox(self.frame)
        self.com_list_combobox.setGeometry(QtCore.QRect(160, 40, 431, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.com_list_combobox.setFont(font)
        self.com_list_combobox.setObjectName("com_list_combobox")
        self.baundrate_combobox = QtWidgets.QComboBox(self.frame)
        self.baundrate_combobox.setGeometry(QtCore.QRect(160, 90, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.baundrate_combobox.setFont(font)
        self.baundrate_combobox.setObjectName("baundrate_combobox")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(20, 40, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.connect_bttn = QtWidgets.QPushButton(self.frame)
        self.connect_bttn.setGeometry(QtCore.QRect(10, 200, 93, 28))
        self.connect_bttn.setObjectName("connect_bttn")
        self.disconnect_bttn = QtWidgets.QPushButton(self.frame)
        self.disconnect_bttn.setGeometry(QtCore.QRect(120, 200, 93, 28))
        self.disconnect_bttn.setObjectName("disconnect_bttn")
        self.refresh_bttn = QtWidgets.QPushButton(self.frame)
        self.refresh_bttn.setGeometry(QtCore.QRect(220, 200, 93, 28))
        self.refresh_bttn.setObjectName("refresh_bttn")
        SerialPortWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(SerialPortWindow)
        self.statusbar.setObjectName("statusbar")
        SerialPortWindow.setStatusBar(self.statusbar)

        self.retranslateUi(SerialPortWindow)
        QtCore.QMetaObject.connectSlotsByName(SerialPortWindow)

    def retranslateUi(self, SerialPortWindow):
        _translate = QtCore.QCoreApplication.translate
        SerialPortWindow.setWindowTitle(_translate("SerialPortWindow", "MainWindow"))
        self.label_2.setText(_translate("SerialPortWindow", "Baundrate:"))
        self.label.setText(_translate("SerialPortWindow", "Ports:"))
        self.connect_bttn.setText(_translate("SerialPortWindow", "Connect"))
        self.disconnect_bttn.setText(_translate("SerialPortWindow", "Disconnect"))
        self.refresh_bttn.setText(_translate("SerialPortWindow", "Refresh"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SerialPortWindow = QtWidgets.QMainWindow()
    ui = Ui_SerialPortWindow()
    ui.setupUi(SerialPortWindow)
    SerialPortWindow.show()
    sys.exit(app.exec_())
